apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowflake-app-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - snowflake.dev.local
      secretName: snowflake-app-tls
  rules:
    - host: snowflake.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snowflake-app-service
                port:
                  number: 80

